### ISSUE TITLE
Display more than one category per page?

### ISSUE THREAD

**Issue by keepsmilyn** [joerivanveen/faq-with-categories#2]
Can more than 1 category be shown on a single page? We have tried using the category shortcode of:
[faq-with-categories category=”category name 1″] 
[faq-with-categories category=”category name 2″] 

Unfortunately it only displays content from 1 category, not 2 or more on the same page.

We want to be able to display “general categories” and then certain specific categories on different pages as well. For example: “General Fashion FAQs”, “Only Womens Clothing FAQs”, “Only Mens Clothing FAQs”, how do we go about this??

Secondly, can they be sorted alphabetically or numerically? They seem to be displaying in order of date last added at the top which isnt necessarily preferred.

**Comment by joerivanveen** [comment]
https://wordpress.org/support/topic/more-than-one-category-be-shown-on-1-page

**Comment by joerivanveen** [comment]
Showing multiple categories on a single page is now supported, from release 1.3.0.
